apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: checkout
spec:
  params:
  - name: repo-url
    type: string
  steps:
  - name: checkout
    image: bitnami/git:latest
    command: [git]
    args: ["clone" "$(params.repo-url)"]

